CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Author" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Biography" text,
    CONSTRAINT "PK_Author" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(256) NOT NULL,
    "Isbn" character varying(20) NOT NULL,
    "PublicationYear" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);

CREATE TABLE "Members" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(320) NOT NULL,
    "PhoneNumber" text,
    CONSTRAINT "PK_Members" PRIMARY KEY ("Id")
);

CREATE TABLE "AuthorBook" (
    "AuthorsId" integer NOT NULL,
    "BooksId" integer NOT NULL,
    CONSTRAINT "PK_AuthorBook" PRIMARY KEY ("AuthorsId", "BooksId"),
    CONSTRAINT "FK_AuthorBook_Author_AuthorsId" FOREIGN KEY ("AuthorsId") REFERENCES "Author" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AuthorBook_Books_BooksId" FOREIGN KEY ("BooksId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Loans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MemberId" integer NOT NULL,
    "BookId" integer NOT NULL,
    "LoanDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Loans_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Loans_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AuthorBook_BooksId" ON "AuthorBook" ("BooksId");

CREATE UNIQUE INDEX "IX_Books_Isbn" ON "Books" ("Isbn");

CREATE INDEX "IX_Loans_BookId" ON "Loans" ("BookId");

CREATE INDEX "IX_Loans_MemberId" ON "Loans" ("MemberId");

CREATE UNIQUE INDEX "IX_Members_Email" ON "Members" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304151507_InitialSchema', '10.0.3');

COMMIT;

