START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304094141_BooksNeedAuthors', '10.0.3');

COMMIT;

START TRANSACTION;
CREATE TABLE "Author" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Biography" text,
    CONSTRAINT "PK_Author" PRIMARY KEY ("Id")
);

CREATE TABLE "AuthorBook" (
    "AuthorsId" integer NOT NULL,
    "BooksId" integer NOT NULL,
    CONSTRAINT "PK_AuthorBook" PRIMARY KEY ("AuthorsId", "BooksId"),
    CONSTRAINT "FK_AuthorBook_Author_AuthorsId" FOREIGN KEY ("AuthorsId") REFERENCES "Author" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AuthorBook_Books_BooksId" FOREIGN KEY ("BooksId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AuthorBook_BooksId" ON "AuthorBook" ("BooksId");


-- Backfill: create Unknown Author once
INSERT INTO "Authors" ("FirstName", "LastName", "Biography")
SELECT 'Unknown', 'Author', 'Auto-created during V002 migration to satisfy required author relationship'
WHERE NOT EXISTS (
  SELECT 1 FROM "Authors" WHERE "FirstName"='Unknown' AND "LastName"='Author'
);

-- Backfill: attach Unknown Author to all books without any author
INSERT INTO "BookAuthors" ("BookId", "AuthorId")
SELECT b."Id", a."Id"
FROM "Books" b
JOIN "Authors" a ON a."FirstName"='Unknown' AND a."LastName"='Author'
WHERE NOT EXISTS (
  SELECT 1 FROM "BookAuthors" ba WHERE ba."BookId" = b."Id"
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304121802_V002_BooksNeedAuthors', '10.0.3');

COMMIT;

