START TRANSACTION;
CREATE TABLE "Author" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Biography" text,
    CONSTRAINT "PK_Author" PRIMARY KEY ("Id")
);

CREATE TABLE "AuthorBook" (
    "AuthorsId" integer NOT NULL,
    "BooksId" integer NOT NULL,
    CONSTRAINT "PK_AuthorBook" PRIMARY KEY ("AuthorsId", "BooksId"),
    CONSTRAINT "FK_AuthorBook_Author_AuthorsId" FOREIGN KEY ("AuthorsId") REFERENCES "Author" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AuthorBook_Books_BooksId" FOREIGN KEY ("BooksId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AuthorBook_BooksId" ON "AuthorBook" ("BooksId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304121802_V002_BooksNeedAuthors', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Members" ADD "PhoneNumber" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304143757_V003_AddMemberPhoneNumber', '10.0.3');

COMMIT;
